sudo: false
language: php

php:
- 7.1
- 7.2
- 7.3
- 7.4
- nightly

matrix:
  fast_finish: true
  allow_failures:
  - php: nightly
  - php: 7.1

stages:
- check
- test
- coverage
- deploy

jobs:
  include:
  - stage: check
    php: 7.2
    script:
    - ./vendor/bin/phpcs
  - stage: coverage
    if: branch = master AND type = push
    php: 7.2
    env: TEST_COVERAGE=true
    before_install:
    - phpenv config-rm xdebug.ini
    - composer self-update
    - composer require --dev --no-update satooshi/php-coveralls
    script:
    - ./vendor/bin/phpunit -c phpunit.travis.xml --coverage-clover build/logs/clover.xml
    after_script:
    - ./vendor/bin/coveralls -v
  - stage: deploy
    if: type = push AND branch = master
    script:
    - openssl aes-256-cbc -K $encrypted_13cee3189705_key -iv $encrypted_13cee3189705_iv -in deploy-key.enc -out deploy-key -d && chmod 600 deploy-key;
    - ./vendor/bin/phing deploy;


before_install:
- composer self-update
install:
- travis_retry composer install --no-interaction --ignore-platform-reqs
script:
- ./vendor/bin/phpunit -c phpunit.travis.xml
